- .gitignore
- pom.xml
- src/main/java/com/onelogin/saml/Response.java
So, I love your toolkit and is one of the primary reasons why I'm choosing OneLogin over Okta.  Your toolkit is so straightforward and easy to use whereas Okta just suggested using opensaml and I frankly just don't have the time or the patience to deal with that library.
Anyway, funny enough, I used your toolkit with immediate (and very easy) success with Okta.  HOWEVER, when using it with OneLogin the response is never valid because the audience can not be located in the assertion.  As a quick hack to get around it so I could finish my evaluation of both OneLogin and Okta I did the changes included in this pull request.  Perhaps I configured my Test SAML connector wrong in OneLogin - I don't know.  BUT, I have to say, it is hilarious that your toolkit worked out of the box with Okta (I …
> Hack to get around OneLogin not returning an audience

- src/main/java/com/onelogin/saml/AuthRequest.java
According to [SAML V2 Core](http://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) (8.2.1 Unspecified) and [SAML V2 Errata 05](http://docs.oasis-open.org/security/saml/v2.0/errata05/os/saml-v2.0-errata05-os.pdf) (E84: Incorrect NameID Format constant), NameIDFormat in AuthnRequest should be <code>"urn:oasis:names:tc:SAML:<b>1.1</b>:nameid-format:unspecified"</code>
> Modified AuthRequest NameIdFormat to comply with SAML v2 specification

- src/main/java/com/onelogin/saml/Response.java
getLocalName causes NullPointerExceptions if the XML is fancy formatted with new lines.  This is because getLocalName() will always return null if the node type is not Element or Attribute.  The libraries treat new lines in SubjectConfirmation as child nodes which causes getLocalName() to be null.
> getLocalName causes NPE if xml has \n

- src/main/java/com/onelogin/AccountSettings.java
- src/main/java/com/onelogin/saml/Response.java
Added support for loading certificate that's not base64 encoded, more meaningful error messages, also changed `getAttribute()` 
We should expect `getAttribute("email")` to return the first email (if >1)`example@gmail.com` instead of  `{example@gmail.com}` which is result of `ArrayList<String>::toString()`
> Error Message Change + getAttribute() change

- core/src/test/java/com/onelogin/saml2/test/settings/SettingBuilderTest.java
`maven install` now builds successfully.
> Update SettingBuilderTest.checkSettings to match config.certstring.properties

- src/main/java/com/onelogin/saml/Utils.java
Java is able to process path with "/"
> Fix #44.Utils.validateXML fails with NullPointerException on Windows

- core/pom.xml
- pom.xml
- samples/java-saml-jspsample/pom.xml
- samples/pom.xml
This:
* sets up maven-release-plugin to release to central through [Sonatype's OSS repository hosting](http://central.sonatype.org/pages/ossrh-guide.html)
* adds metadata to the poms [required](http://central.sonatype.org/pages/requirements.html) for releasing to central
* configures [signing the released artifacts](http://central.sonatype.org/pages/apache-maven.html#gpg-signed-components) using gpg and maven-gpg-plugin
* cleans up some duplicated properties/unneded dependencies
* Set up an account with Sonatype as documented [here](http://central.sonatype.org/pages/ossrh-guide.html#create-a-ticket-with-sonatype)
* Make sure the ticket is marked as Resolved before proceeding
* Add the account credentials to your `$HOME/.m2/settings.xml`:
```
<settings>
...
<servers>
<server> …
```
> Prepare poms for release

- core/src/main/java/com/onelogin/saml2/Auth.java
- core/src/main/java/com/onelogin/saml2/authn/AuthnRequest.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutRequest.java
- core/src/main/java/com/onelogin/saml2/util/Util.java
- core/src/test/java/com/onelogin/saml2/test/AuthTest.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnRequestTest.java
- core/src/test/java/com/onelogin/saml2/test/logout/LogoutRequestTest.java
- core/src/test/java/com/onelogin/saml2/test/util/UtilsTest.java
- Auth now has getLastLoginRequestId/getLastLogoutRequestId methods
that allow retrieving the id of the generated AuthnRequest/LogoutRequest
message to be used in response validation
> #60: allow retrieving the generated request ids

- README.md
- core/pom.xml
- core/src/main/java/com/onelogin/saml2/Auth.java
- core/src/test/java/com/onelogin/saml2/test/AuthTest.java
- core/src/test/java/com/onelogin/saml2/test/MetadataTest.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnRequestTest.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnResponseTest.java
- core/src/test/java/com/onelogin/saml2/test/logout/LogoutRequestTest.java
- core/src/test/java/com/onelogin/saml2/test/logout/LogoutResponseTest.java
- core/src/test/java/com/onelogin/saml2/test/model/ContactTest.java
- core/src/test/java/com/onelogin/saml2/test/model/OrganizationTest.java
- core/src/test/java/com/onelogin/saml2/test/model/SamlResponseStatusTest.java
- core/src/test/java/com/onelogin/saml2/test/settings/Saml2SettingsTest.java
- core/src/test/java/com/onelogin/saml2/test/settings/SettingBuilderTest.java
- core/src/test/java/com/onelogin/saml2/test/util/UtilsTest.java
Removed the PowerMock javaagents as this is what causes problems with the bytecode verifier. Tests now pass in JDK8.
> Remove power mock agents

- core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java
- core/src/main/java/com/onelogin/saml2/settings/Saml2Settings.java
- core/src/main/java/com/onelogin/saml2/settings/SettingsBuilder.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnResponseTest.java
- core/src/test/resources/data/responses/invalids/invalid_subjectconfirmation_multiple_issues.xml
- core/src/test/resources/data/responses/invalids/invalid_unpaired_inresponsesto.xml
- core/src/test/resources/data/responses/valid_idp_initiated_response.xml
This fixes a few cases where the InResponseTo attribute wasn't checked correctly:
* reject Responses with no InResponseTo if one was provided as an argument to validate
* i.e. if you call `validate('id')`, and the Response had no `InResponseTo` this was previously allowed, now is denied
* reject Responses with a InResponseTo if null was provided as an argument to validate
* this is disabled by default, enabled by `Saml2Settings.rejectUnsolicitedResponsesWithInResponseTo`
* i.e. if you call `validate(null)` and the Response had a `InResponseTo` this was previously always allowed, now will only be allowed when `rejectUnsolicitedResponsesWithInResponseTo` is `false` (which is the default) 
* reject SubjectConfirmationData without a InResponseTo, when the Response has one
* i.e. if the …
> #62: check InResponseTo in Response more strictly

- core/pom.xml
Use provided scope for the servlet-api dependency as this is expected to be provided by the servlet container.
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope
> set scope=provided for javax.servlet:servlet-api

- core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java
- core/src/main/java/com/onelogin/saml2/util/Util.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnResponseTest.java
- core/src/test/java/com/onelogin/saml2/test/util/UtilsTest.java
- core/src/test/resources/data/responses/invalids/attacks/response_with_spoofed_response_signature.xml
- core/src/test/resources/logback-test.xml
- toolkit/src/test/resources/logback-test.xml
- checks that the found Signature elements match their expected schema locations, and that there's only one of each
- make sure the expected Signatures are always verified
- a few other small hardenings
> fixes #78: make sure the correct Signature elements are  verified

- core/src/main/java/com/onelogin/saml2/logout/LogoutResponse.java
- core/src/main/java/com/onelogin/saml2/settings/Saml2Settings.java
- core/src/main/java/com/onelogin/saml2/settings/SettingsBuilder.java
- core/src/test/java/com/onelogin/saml2/test/settings/SettingBuilderTest.java
- core/src/test/resources/config/config.all.properties
- core/src/test/resources/config/config.different.properties
- core/src/test/resources/config/config.somevaluesempty.properties
- core/src/test/resources/onelogin.saml.properties
- samples/java-saml-jspsample/src/main/resources/onelogin.saml.properties
- toolkit/src/main/java/com/onelogin/saml2/Auth.java
- toolkit/src/test/java/com/onelogin/saml2/test/AuthTest.java
Added a property which can allow the library to use separate URLs for SLO request/response. New property value
onelogin.saml2.idp.single_logout_service.response.url
If the new property is not set/blank/invalid url, the logout url specified with onelogin.saml2.idp.single_logout_service.url will be used.
> V2.0.0 issue 80

- core/src/main/java/com/onelogin/saml2/util/SchemaFactory.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnResponseTest.java
Avoid sharing a static `javax.xml.validation.SchemaFactory` which is not thread safe - this caused failures when trying to do process Responses in multiple threads concurrently.
> fixes #83: don't share a SchemaFactory between instances

- toolkit/src/main/java/com/onelogin/saml2/Auth.java
- toolkit/src/test/java/com/onelogin/saml2/test/AuthTest.java
Currently it's not possible to have an authn request without a relayState. When a null relayState is provided, then a self routed URL is used instead. If an empty string is provided, then relayState is appended as a query parameter without value. A request without a relayState is a valid case and relayState without value does not work ie in ADFS (it results in an MSIS7000 error).
To mitigate this without changing the API too much I've changed login to treat an empty returnTo (relayState) parameter as no relay state. A null returnTo will still result in a self routed URL. I also added a test case for this scenario and extended the Javadocs to inform about the behavior.
> Allow authn request without relayState if relayState is empty

- core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java
- core/src/main/java/com/onelogin/saml2/util/Util.java
XML validation fails when the JVM does not use UTF-8 as the default
encoding.  Added UTF-8 encoding in byte to string conversions in:
* SamlResponse - after base64decode SAMLResponse
* Util.convertDocumentToString()
> Adds UTF-8 encoding when converting bytes to string

- core/src/main/java/com/onelogin/saml2/util/Util.java
Default encoding used in Util.base64encoder() methods.
This commits adds UTF-8 encoding in string <-> byte conversions.
Added Util.toBytesUtf8(String) and Util.toStringUtf8(byte[]).
No tests added for this one. It's a bit messy to test
things that require the JVM defaults to change. We usually
use code analysis tools to detect byte<->string conversion
issues.
> Adds UTF-8 encoding in Util base64 encode/decode

- core/src/main/java/com/onelogin/saml2/util/Util.java
Added a check to see if the JAXP implementation understands features of JAXP 1.5. Concrete example of when this causes problems is when Xerces is on the classpath. Xerces does not support these features which will trigger an exception an cause the XML validation to always fail. When implementing the OneLogin SAML library in an application you don't always have the luxury of kicking Xerces out of the project ;-).
While checking for a string in an exception might seem odd it is actually the Oracle / Java recommended way. There is even a special documentation page for this exact issuet: https://docs.oracle.com/javase/tutorial/jaxp/properties/error.html . I guess Java 9 jigsaw should also be able to fix something like this. Since then the programmer can actually know which implementation …
> Add a check to see if the JAXP implementation understands JAXP 1.5 features

- core/src/main/java/com/onelogin/saml2/util/Util.java
Older versions of sax parser could throw a Throwable that doesn't subclass Exception, so the Exception catch doesn't catch that occurence
> Compatibility with older versions of xerces sax parser

- README.md
- core/src/main/java/com/onelogin/saml2/model/Organization.java
- core/src/main/java/com/onelogin/saml2/settings/Metadata.java
- core/src/main/java/com/onelogin/saml2/settings/SettingsBuilder.java
- core/src/test/java/com/onelogin/saml2/test/model/OrganizationTest.java
- core/src/test/java/com/onelogin/saml2/test/settings/MetadataTest.java
- core/src/test/resources/config/config.all.properties
- core/src/test/resources/config/config.org.localized.properties
- core/src/test/resources/config/config.org.properties
- samples/java-saml-tookit-jspsample/src/main/resources/onelogin.saml.properties
I put the attribute into the `Organization`, class,  and overloaded the constructors, leaving the existing ones with a "en" default value.
This PR allows us to change this attribute without breaking existing configurations (including programmatic ones), even though it won't fully answer issue #102
> Add onelogin.saml2.organization.lang attribute  

- toolkit/src/main/java/com/onelogin/saml2/Auth.java
The `Auth#processSLO()` was checking the wrong setting to decide if the Logout Response message should be signed or not.
> Check the correct setting before signing Logout responses

- samples/java-saml-tookit-jspsample/src/main/webapp/dologin.jsp
Remove the hardcoded context-path for the sample application.
> Fix: gather context path via Java

- README.md
- core/pom.xml
- core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnResponseTest.java
- Fix some spelling issues
- Update readme with latest version
- Make `SamlResponse` a bit more extendable for when special validation logic is required
- Fix a maven warning about `maven-jar-plugin` version missing
> Make SamlResponse slightly more extendable

- README.md
- core/src/main/java/com/onelogin/saml2/authn/AuthnRequest.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutRequest.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutResponse.java
- core/src/main/java/com/onelogin/saml2/settings/Metadata.java
- core/src/main/java/com/onelogin/saml2/settings/Saml2Settings.java
- core/src/main/java/com/onelogin/saml2/settings/SettingsBuilder.java
- core/src/main/java/com/onelogin/saml2/util/Util.java
- core/src/test/java/com/onelogin/saml2/test/settings/Saml2SettingsTest.java
- core/src/test/java/com/onelogin/saml2/test/settings/SettingBuilderTest.java
- core/src/test/java/com/onelogin/saml2/test/util/UtilsTest.java
- core/src/test/resources/config/config.all.properties
- core/src/test/resources/config/config.min_uniqueid.properties
- toolkit/src/test/java/com/onelogin/saml2/test/AuthTest.java
Made it possible to change the prefix of unique ID through properties.
If property is not set the default value of "ONELOGIN_" is used.
This PR overrides #185
> Add a property for unique ID prefix

- core/src/main/java/com/onelogin/saml2/util/Util.java
This changes the XPathFactory call to use a specific XPathFactoryImpl to avoid issues where an environment may be using a default implementation that's incompatible with the code (such as using an outdated Saxon parser). This change attempts to use the default Java implementation, but if that is unavailable will fallback to try to load the default.
This will also help to ensure the XML is always parsed in a consistent manor, since everyone should be using the same XPathFactoryImpl.
This should resolve Issue #191.
> Changed code to use specific XPathFactoryImpl

- core/pom.xml
- toolkit/pom.xml
The current version of the jacoco plugin causes build errors if building with JDK 11. Bumping to the latest works. I have tested this with Jdk 11 and jdk 8. I have been unsuccessful in my archaeological studies trying to locate a JDK7, so not been able to test against that.
> Bump the Jacoco plugin allowing JDK11 builds

- .nvd-suppressions.xml
- .travis.yml
- pom.xml
Proposed changes to introduce [NVD checker](https://jeremylong.github.io/DependencyCheck/).
Related to issue #223 
I included an empty suppressions file for future use.
It is pretty easy to edit. A guide is here https://jeremylong.github.io/DependencyCheck/general/suppression.html
Also correct suppression tags can be copy pasted from the report the tool generates.
The false positive came from an old logback version that has a ServerSocketReceiver related vulnerability. I don't think OneLogin uses that feature, but I thought it would be best to just update the dependency.
> Add NVD checker to travis build

- core/src/main/java/com/onelogin/saml2/settings/Saml2Settings.java
- core/src/test/java/com/onelogin/saml2/test/settings/Saml2SettingsTest.java
- core/src/test/resources/config/config.min_idp_multicert.properties
In Idp configuration settings it was mandatory to have the property for `onelogin.saml2.idp.x509cert` even if it was configured multiple certificates.
This change allows defining only settings for multiple Idp certs when it is not necessary the key X509Cert.
> Allow only multiple certs when checking idp settings.

- core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutRequest.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutResponse.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnResponseTest.java
- core/src/test/java/com/onelogin/saml2/test/logout/LogoutRequestTest.java
- core/src/test/java/com/onelogin/saml2/test/logout/LogoutResponseTest.java
- toolkit/src/main/java/com/onelogin/saml2/Auth.java
- toolkit/src/test/java/com/onelogin/saml2/test/AuthTest.java
Hi, we have a requirement in our product to take different actions based on the exact error with the SAML response (in our case, show the user different documentation pages on how they can fix the problem).
The best way I found to do this which doesn't rely on string matching was to expose the actual exception as in this PR, then use `ValidationException#getErrorCode` to drive the logic.
I have not updated any tests yet, but am happy to do that if you agree this is an acceptable change.
> Expose validation exception in SamlResponse

- core/src/main/java/com/onelogin/saml2/util/Util.java
> fix signature validation issue

- core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnResponseTest.java
The SamlResponse class is basically a function which needs settings, url,
and a saml-response. This commit adds a constructor which takes only those
parameters instead of wrapping them in a HttpRequest.
> [Fix #283] Expose a new constructor for SamlResponse

- .nvd-suppressions.xml
- core/pom.xml
- core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java
- core/src/main/java/com/onelogin/saml2/model/hsm/AzureKeyVault.java
- core/src/main/java/com/onelogin/saml2/model/hsm/HSM.java
- core/src/main/java/com/onelogin/saml2/settings/Saml2Settings.java
- core/src/main/java/com/onelogin/saml2/util/Constants.java
- core/src/main/java/com/onelogin/saml2/util/Util.java
- core/src/test/java/com/onelogin/saml2/test/settings/Saml2SettingsTest.java
- core/src/test/resources/config/config.hsm.properties
- pom.xml
- toolkit/src/test/java/com/onelogin/saml2/test/AuthTest.java
This pull request addresses [#257](https://github.com/onelogin/java-saml/issues/257)
Currently, the library has no support for HSM integration, in particular when it comes to unwrap the key as part of the SAML decryption process.
Hence, this solution will support HSM key unwrapping by setting an HSM object as part of the SAML settings. My requirement was to integrate this library specifically to the Azure Key Vault. However, I have implemented an HSM abstract class in order to allow the possibility of integrating it with other HSMs as well. I have also imported 2 new libraries (for the Azure Key Vault) as optional dependencies since whoever is going to use this library might not require this HSM support. 
I have also upgraded the dependency check plugin to the current latest version …
> Support for unwrapping key via an HSM when decrypting the SAML assertion.

- README.md
- core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutRequest.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutResponse.java
- core/src/main/java/com/onelogin/saml2/settings/Saml2Settings.java
- core/src/main/java/com/onelogin/saml2/settings/SettingsBuilder.java
- core/src/main/java/com/onelogin/saml2/util/Util.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnResponseTest.java
- core/src/test/java/com/onelogin/saml2/test/logout/LogoutRequestTest.java
- core/src/test/java/com/onelogin/saml2/test/logout/LogoutResponseTest.java
- core/src/test/java/com/onelogin/saml2/test/util/UtilsTest.java
- core/src/test/resources/data/metadata/signed_metadata_settings256.xml
- samples/java-saml-tookit-jspsample/src/main/resources/onelogin.saml.properties
- Set SHA-256 as default alg in settings
- Support Alg Deprecated rejection by the use of a new setting.
- Notify with Logger.info if sha-1 alg used on Signature
> See #294 Support Alg Deprecated rejection.

- core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java
The query and queryAssertion methods are really useful when creating
extensions of SamlResponse that need to expose other information that
the plain java-saml library does not (like the response issue instant,
or any custom contents of the AuthnContext in the assertion auth
statement). Having these two methods private forces the extender to
reimplement them from scratch, probably by copy-and-paste, which is
clearly sub-optimal.
A concrete example: the Italian SPID authentication system expects the "authentication level" to be specified within the `AuthnContextClassRef` element. Also, it recommends to track the response issue instant, so when using java-saml to implement a SPID SP, these two pieces of information should be extracted from the response.
Please note I also removed a clear …
> Make SamlResponse more extensible

- core/src/main/java/com/onelogin/saml2/logout/LogoutRequest.java
Two reasons for removal:
- avoid the need of a useless try/catch on consuming code
- align API to LogoutResponse.isValid() and SamlResponse.isValid()
The code is backward compatible, because an existing surrounding
try/catch(Exception) won't cause a compilation error after the change.
> Remove the useless Exception throws declaration in LogoutRequest.isValid

- core/src/main/java/com/onelogin/saml2/logout/LogoutRequest.java
- toolkit/src/main/java/com/onelogin/saml2/Auth.java
This exception is indeed never thrown and it's a checked one, so it
makes using Auth.logout heavier then necessary. java-saml already has an
abundance of checked exceptions to handle, some of which could easily
be translated into unchecked ones or caught and recovered cleanly, this
is why I think that, if a useless exception declaration is found, it
should better be removed.
This indeed is a small source-incompatible change as soon as the
consumer code is catching XMLEntityException explicitly (rather than
SAMLException, Exception or Throwable). However, fixing this is trivial,
just remove XMLEntityException from the catch clause (which will never
be triggered anyway).
> Remove useless XMLEntityException declaration in logout throws clause

- core/src/main/java/com/onelogin/saml2/authn/AuthnRequest.java
- core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java
- core/src/main/java/com/onelogin/saml2/exception/ValidationError.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutRequest.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutResponse.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnRequestTest.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnResponseTest.java
- core/src/test/java/com/onelogin/saml2/test/logout/LogoutRequestTest.java
- core/src/test/java/com/onelogin/saml2/test/logout/LogoutResponseTest.java
- toolkit/src/main/java/com/onelogin/saml2/Auth.java
- toolkit/src/test/java/com/onelogin/saml2/test/AuthTest.java
Each message (AuthnRequest, SamlResponse, LogoutRequest and
LogoutResponse) have been enhanced to expose their issue instant. This
is useful for logging purposes (i.e.: you want to track each request
you generate and each response you receive, along with their issue
instant), which is also required when implementing a SPID Service
Provider (SPID is a SAML 2.0-based federated system used by the Italian
government).
I also tried to implement some tests for Auth, but I did not succeed for
the "received message" scenario, because, to be coherent with the "last
message id" case, the "last message issue instant" information is set
on the Auth instance only if the message processing succeeds (i.e.: the
processed message is valid). The test data used here seems to fail
validation because of time …
> Add Auth.getLastMessageIssueInstant and Auth.getLastRequestIssueInstant

- core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java
- toolkit/src/main/java/com/onelogin/saml2/Auth.java
- toolkit/src/test/java/com/onelogin/saml2/test/AuthTest.java
The map returned by SamlResposne containing the attributes returned by
the IdP now preserves the order in which such attributes appear in the
SAML response XML. This is not strictly mandatory, but a plus.
Indeed, the test method
com.onelogin.saml2.test.AuthTest.testProcessResponse() was not
deterministic before this change: indeed, the iteration order of HashMap
is undetermined so expecting to see attribute names in a given order
could lead to a test failure. This change also fixes this and attribute
names are expected now to be seen in the order in which the
corresponding attributes appear in the test XML file.
This closes #330.
> Make the SamlResponse returned attribute map preserve attribute order

- README.md
- toolkit/src/main/java/com/onelogin/saml2/Auth.java
I know this might be considered an opinionated cosmetic change, but please read on the rationale behind this renaming.
In the most simple case, the RelayState may be used as a "returnUrl",
but I think it's important to underline that the RelayState does not
necessarily need to be a return URL. Indeed, the SAML 2.0 specification
clarifies that a limit of max 80 characters exists for it (at least
in the case of the HTTP-Redirect binding) and that a protection method
against tampering is suggested.
Therefore, a return URL in general would probably be a non-ideal use of
the RelayState parameter, so let's give the latter the relevance it
deserves.
> Clarify the real nature of the RelayState parameter for SSO and SLO

- core/src/main/java/com/onelogin/saml2/util/SchemaFactory.java
- core/src/main/resources/schemas/XMLSchema.dtd
- core/src/main/resources/schemas/datatypes.dtd
- core/src/main/resources/schemas/xenc-schema.xsd
Schemas in main/resources were not correctly used on schema loading
when java-saml was used as a JAR in a consuming application. It seems
like the local XSD files for imported schemas were used only when
running unit tests, while remote HTTP lookups from the W3C website were
made when using java-saml as a JAR. Now a LSResoureResolver is set on
the schema factory so that any known XSD or DTD is loaded from the
classpath, even when inside a JAR. Any other (unknown) schema is
resolved in the standard way (and may involve a remote call). Also, in
the unlikely event that retrieving the local copy of the XSD/DTD is
impossible, a fallback mechanism ensures the standard resolution is
performed.
Please note that the online version of xenc-schema.xsd contains a
reference to the XML Schema DTD. Now …
> Ensure local resolution of schemas (and DTDs)

- core/src/main/java/com/onelogin/saml2/authn/AuthnRequest.java
- core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutRequest.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutResponse.java
- core/src/main/java/com/onelogin/saml2/settings/Metadata.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnRequestTest.java
- core/src/test/java/com/onelogin/saml2/test/logout/LogoutRequestTest.java
- core/src/test/java/com/onelogin/saml2/test/logout/LogoutResponseTest.java
- core/src/test/java/com/onelogin/saml2/test/settings/MetadataTest.java
This change allows for any java-saml consumer to extend the standard
classes used to generate SAML messages (AuthnRequest, LogoutRequest and
LogoutResponse), as well as the metadata, and provide their own logic to
post-process the default XML produced by java-saml. Any extension class
will then be able to transform or enrich the generated XML as required,
before the framework applies encoding, encryption or signing.
This is the implementation of the idea I was thinking of when writing https://github.com/onelogin/java-saml/issues/265#issuecomment-811866110. I think this is the most non-instrusive and not too dirty way to let java-saml be extended by consumers. Of course, this is just one step: if the consumer wants to use the `Auth` class as well, the other problem I mentioned in the above …
> Allow for extension classes to post-process generated XML

- core/src/main/java/com/onelogin/saml2/logout/LogoutResponse.java
- core/src/test/java/com/onelogin/saml2/test/logout/LogoutResponseTest.java
An overload of build() has been added to supply a SamlResponseStatus,
so that it's possible to specify a more complex response status in the
generated LogoutResponse. A typical example is the case of a partial
logout, which needs a top-level
urn:oasis:names:tc:SAML:2.0:status:Responder status code and a
second-level
urn:oasis:names:tc:SAML:2.0:status:PartialLogout one. Also, a status
message can also be added now.
Closes #342.
> Support more complex response statuses in LogoutResponse generation

- core/src/main/java/com/onelogin/saml2/authn/AuthnRequest.java
- core/src/main/java/com/onelogin/saml2/authn/AuthnRequestParams.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutRequest.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutRequestParams.java
- core/src/main/java/com/onelogin/saml2/settings/Metadata.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnRequestTest.java
- core/src/test/java/com/onelogin/saml2/test/logout/LogoutRequestTest.java
- core/src/test/java/com/onelogin/saml2/test/logout/LogoutResponseTest.java
- toolkit/src/main/java/com/onelogin/saml2/Auth.java
- toolkit/src/test/java/com/onelogin/saml2/test/AuthTest.java
This PR is made of:
- an `AuthRequest` refactoring extracted from #307
- a `LogoutRequest` refactoring picked from my own fork (for which I hadn't provided any PR yet because it was relying on other changes)
Benefits of this refactoring:
- it polishes the `AuthnRequest`, `LogoutRequest` and `Auth` APIs: all those overridings were honestly cluttering the API and they were not easily extensible
- it improves library evolution: any future evolution of this library which requires to add further input parameters to the `AuthnRequest` and `LogoutRequest` generation process, may simply extend `AuthnRequestParams` and `LogoutRequestParams` without the need to further touch the API of  `AuthnRequest`, `LogoutRequest` and `Auth` classes (or to provide even more overridings); this allows, for …
> Improve authentication and logout request input params API

- core/src/main/java/com/onelogin/saml2/authn/AuthnRequest.java
- core/src/main/java/com/onelogin/saml2/authn/AuthnRequestParams.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnRequestTest.java
> Allow to control NameIDPolicy.AllowCreate attribute on AuthnRequest

- README.md
- core/src/main/java/com/onelogin/saml2/model/Contact.java
- core/src/main/java/com/onelogin/saml2/settings/Metadata.java
- core/src/main/java/com/onelogin/saml2/settings/Saml2Settings.java
- core/src/main/java/com/onelogin/saml2/settings/SettingsBuilder.java
- core/src/main/java/com/onelogin/saml2/util/Constants.java
- core/src/test/java/com/onelogin/saml2/test/settings/IdPMetadataParserTest.java
- core/src/test/java/com/onelogin/saml2/test/settings/MetadataTest.java
- core/src/test/java/com/onelogin/saml2/test/settings/Saml2SettingsTest.java
- core/src/test/java/com/onelogin/saml2/test/settings/SettingBuilderTest.java
- core/src/test/resources/config/config.all.properties
- core/src/test/resources/config/config.all_specialchars.properties
- core/src/test/resources/config/config.allerrors.properties
- core/src/test/resources/config/config.sperrors.properties
- toolkit/src/test/java/com/onelogin/saml2/test/AuthTest.java
This change adds the ability to specify all data for the Service Provider contacts.
However, it maintains backward compatibility with the old limited support offered for the technical and support contact given name and e-mail address only, although documentation now suggests a more comprehensive approach.
Having the ability to specify rich data for contact types is a key feature required to implement SPID.
This PR also fixes the contact settings validation described in #353.
> Improve SP contacts

- core/src/main/java/com/onelogin/saml2/util/Util.java
Prevent xerces libraries from outputting to stderr and give users the ability to control logging.
> Update parseXML to use XMLErrorAccumulatorHandler

- README.md
- update dependency version (2.6.0 -> 2.8.0) in README
- add TOC for navigation
> docs: update dependency version used in README and add TOC

- core/pom.xml
Updating xmlsec to avoid pulling in a version of woodstox-core that is vulnerable to Improper Restriction of XML eXternal Entity (XXE) Reference,
> Updated org.apache.santuario:xmlsec to version 2.3.0

- core/pom.xml
- core/src/main/java/com/onelogin/saml2/authn/SamlResponse.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutRequest.java
- core/src/main/java/com/onelogin/saml2/logout/LogoutResponse.java
- core/src/main/java/com/onelogin/saml2/util/Util.java
- core/src/test/java/com/onelogin/saml2/test/authn/AuthnResponseTest.java
- core/src/test/java/com/onelogin/saml2/test/util/UtilsTest.java
- core/src/test/java/com/onelogin/saml2/util/DateTimeTestUtils.java
- toolkit/pom.xml
- toolkit/src/main/java/com/onelogin/saml2/Auth.java
- toolkit/src/test/java/com/onelogin/saml2/test/AuthTest.java
> Use java.time instead of joda-time
